### ISSUE TITLE
Struct arrays

### ISSUE THREAD

**Issue by jonathf** [jonathf/matlab2cpp#12]
Structures are neither recognized nor processed

Example:
a = struct                                                                                                        
a(1).b = 4                                                                                                        
a(1).c = "5"

**Comment by jonathf** [comment]
@aronandersson : sikker på at denne skal være high prio/prio2?

Dette er struct arrays, ikke structs.

**Comment by aronandersson** [comment]
Ok, jag ser ingen issue för vanliga structs. Är det meningen att structs ska fungera nu? Jag ser att deklarationer för structs genereras i cpp-filen, men variablerna finns inte i .py filen.

**Comment by jonathf** [comment]
Det må jeg få lagt inn. På TODO nå.

**Comment by jonathf** [comment]
Structs er nå med i .py-filen. Man kan også legge til variabler i structen med å skrive nye navn+type i tilsvarende format.
