### ISSUE TITLE
Converting a handle Class 

### ISSUE THREAD

**Issue by k88joshi** [jonathf/matlab2cpp#127]
I have a handle class written in MATLAB and would like to convert it to C++ code.  I am not sure if this can be done using the mat2cpp tool.  Would I have to bring out each function from the class to create the conversion? Can I put the underlying functions within the class in one m-file and convert it ?

**Comment by jonathf** [comment]
Unfortunatly the tool does not support classes currently. You will have to move them out if the tool can have any chance of translating your code correctly.
