### ISSUE TITLE
armadillo.py:77 TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by moe123** [jonathf/matlab2cpp#137]
File ".../python3.6/site-packages/matlab2cpp/rules/armadillo.py", line 77, in configure_arg
    elif node.mem > 1 and node.dim == 0:

node.mem is None, initialize to explicit integer value.

**Comment by jonathf** [comment]
I apologies, but this project is currently unmaintained. There will therefore not be any more bugfixes unless someone takes ownership. I've added a note to the frontpage now to make everyone aware.

**Comment by moe123** [comment]
ah ok sad 8-) that was a good conformity helper tool to verify implementations without opening mat***$!!.
