### ISSUE TITLE
Mer windowsproblem

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#2]
Antlr returnerar:

line 1:11 token recognition error at: '\r'
line 2:14 token recognition error at: '\r'
line 3:18 token recognition error at: '\r'
line 4:18 token recognition error at: '\r'
line 5:17 token recognition error at: '\r'
line 6:17 token recognition error at: '\r'
line 7:12 token recognition error at: '\r'
line 8:7 token recognition error at: '\r'
line 9:10 token recognition error at: '\r'
line 10:14 token recognition error at: '\r'
line 11:14 token recognition error at: '\r'
line 12:13 token recognition error at: '\r'
line 13:13 token recognition error at: '\r'
line 14:8 token recognition error at: '\r'
....

för alla filer. Så uppenbarligen är det fortfarande något fel i preprocesseringen.

**Comment by jonathf** [comment]
Prøv nå.

**Comment by aronandersson** [comment]
Samma problem fortfarande.

**Comment by jonathf** [comment]
Oki. Ser at editoren jeg bruker i Windows ikke bruker '\r\n', men har klart å replisere problemet nå. Fikset nå.
