### ISSUE TITLE
Format strings

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#23]
Jag får ett oförståeligt felmedellande:

    reading file...
    running preproc...
    writing preproc...
    building token-tree...
    Traceback (most recent call last):
      File ".\mconvert.py", line 42, in <module>
        tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
      File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 150, in main
        tree = build("."+filename)
      File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 34, in build
        input = antlr.FileStream(arg)
      File "C:\Python27\lib\site-packages\antlr4\FileStream.py", line 49, in __init__
        data = codecs.decode(bytes, encoding)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 335: ordinal not in range(128)

för följande fil:

    %clear X % remove existing value of X
    %tol = 1.e-8; % preset tolerance (10-8)
    maxiter = N; % maximum number of iterations
    relerr = inf; % initialize relative error to large value
    niter = 1; % initialize iteration counter
    S = diag( diag(A) ); % diagonal of A
    T = S - A; % off-diagonal of A
    X(:,1) = zeros(size(b)); % initial guess (x = 0)
    
    while relerr > tol && niter< maxiter, % iterate until convergence, or maximum iterations
       X(:,niter+1) = S \ (b+T*X(:,niter));
       relerr = norm(X(:,niter+1)-X(:,niter),inf)/norm(X(:,niter+1),inf);
       niter = niter+1; % increment iteration counter
    end
    fprintf( '\n\nAfter %g iterations of Jacobi”s method the relative error is %g.\n', niter, relerr )
    %X(:,niter);

Om jag kommenterar ut linjen med fprintf så fungerar det.

**Comment by jonathf** [comment]
Fixed with a small temporary hack (substituting '%' with '_' in quotes)
