### ISSUE TITLE
Nästa krash...

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#3]
Traceback (most recent call last):
  File "D:\Projects\emc2\matlab2cpp\mconvert.py", line 39, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 169, in main
    from ``__cfg__`` import scope
ImportError: No module named ``__cfg__``

``__cfg__.py`` ser ut så här:

  # Supplement file
  #
  # Valid inputs:
  # float
  # int
  # fvec
  # ivec
  # frowvec
  # irowvec
  # fmat
  # imat
  
  scope = {}
  
  main = scope["main"] = {}
  main["y"] = "" # ivec
  main["x"] = "" # irowvec

**Comment by jonathf** [comment]
Hm... sliter litt mer med å reprodusere denne.

Kan du sende meg:
* filen du prøver å konvertere
* utskrift fra kjøring med '-d' aktivert

**Comment by aronandersson** [comment]
Jag får samma fel med alla filer. För några får jag också fel från antlr:

reading file...
running preproc...
writing preproc...
building token-tree...
line 8:10 extraneous input '\r' expecting '
}'
writing pickle...
writing backup...
cfg found!
loading cfg...
> c:\python27\lib\site-packages\matlab2cpp\__init__.py(171)main()
-> shutil.copyfile(filename + ".py", "__cfg__.py")
(Pdb) print os.getcwd()
D:\Projects\emc2\wdir
(Pdb) c
Traceback (most recent call last):
  File "D:\Projects\emc2\matlab2cpp\mconvert.py", line 39, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 171, in
main
    shutil.copyfile(filename + ".py", "__cfg__.py")
ImportError: No module named __cfg__

2015-03-12 11:22 GMT+01:00 jonathf <notifications@github.com>:

> Hm... sliter litt mer med å reprodusere denne.
>
> Kan du sende meg:
>
>    - filen du prøver å konvertere
>    - utskrift fra kjøring med '-d' aktivert
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonathf/matlab2cpp/issues/3#issuecomment-78454728>.
>

function esigma = EMIT_Proc_Mandrel_FindESigma(PLF,spacing,strnum,cplt_index,CumThick);
% This function calculates the effective sigma for a given completion
%
% function esigma = EMIT_Proc_Mandrel_FindESigma(PLF,spacing,cprs,completion,constants)
%
% IN:
%   PLF : DCB phase for a non corroded joint
%   cprs : relative mu
%   completion : structure containing strnum (number of strings in the
%       completion - from 1 to 4), csg1_OD (first string outer diameter - add 
%       values for csg2_OD or other if needed) and csg1_WT (first string wall 
%       thickness - add values for csg2_WT or other if needed)

phi_err = 0.1;

V_ref_LS = -7.2424e-007 +9.0329e-004i;
V_ref_SS = -0.0000 + 0.0016i;

CSIZ = CumThick(cplt_index,2); % inner casing OD
WT0 = EMIT_Init_CsgThick(CSIZ,CumThick(cplt_index,3)); % inner casing thickness
WT1 = CumThick(cplt_index,1)-WT0; % Total extra thickness

esigma = sig;
%+- OmniWorks Replacement History - psp_op`emit_matlab:EMIT_Proc_Mandrel_FindESigma.m;1
%       1*[1307038] 14-DEC-2009 16:20:28 (GMT) JCalvez
%         "Find effective sigma for multiple string model"
%+- OmniWorks Replacement History - psp_op`emit_matlab:EMIT_Proc_Mandrel_FindESigma.m;1

**Comment by jonathf** [comment]
Oki. Jeg _tror_ jeg har klart å gripe tak i kjernen av problemet. Prøv igjen nå.

**Comment by aronandersson** [comment]
Ok, nu fungerar det för vissa filer, men för till exempel emit.m får jag nu:

reading file...
running preproc...
writing preproc...
building token-tree...
writing pickle...
writing backup...
cfg found!
loading cfg...
loading scope...
dumping scope...
generate tree...
iterating 73 nodes
WT0 Var TYPE unknown
 Int int int
cplt_index Var TYPE unknown
 Int int int
cplt_index Var TYPE unknown
 Float float float
 Float float float
 Neg TYPE expression
CumThick Get TYPE unknown
CumThick Get TYPE unknown
CSIZ Var TYPE unknown
 Int int int
cplt_index Var TYPE unknown
 Ifloat TYPE ifloat
iterating 73 nodes
 25           program Program    program      TYPE
  1                    Includes   program      TYPE
  1           armadillo Include    program      TYPE
  1           usingarma Include    program      TYPE
  0 EMIT_Proc_Mandrel_FindESigma Func       func_return  TYPE
  6                     Declares   func_return  TYPE
  6              phi_err Declare    unknown      TYPE
  6             V_ref_LS Declare    unknown      TYPE
  6             V_ref_SS Declare    unknown      TYPE
  6                 CSIZ Declare    unknown      TYPE
  6                  WT0 Declare    unknown      TYPE
  6                  WT1 Declare    unknown      TYPE
  6               esigma Declare    unknown      TYPE
  6                  sig Declare    unknown      TYPE
  7                     Returns    func_return  TYPE
  7               esigma Var        unknown      TYPE
  8                     Params     func_return  TYPE
  8                  PLF Var        unknown      TYPE
  8              spacing Var        unknown      TYPE
  8               strnum Var        unknown      TYPE
  8           cplt_index Var        unknown      TYPE
  8             CumThick Var        unknown      TYPE
  9                     Block      code_block   TYPE
  0                      Assign     unknown      TYPE
 10               phi_err Var        unknown      TYPE
 11                       Float      float        float
  0                      Assign     unknown      TYPE
 12              V_ref_LS Var        unknown      TYPE
 13                       Plus       expression   TYPE
 13                        Neg        expression   TYPE
 13                         Float      float        float  '%(value)s'
 13                        Ifloat     ifloat       TYPE
  0                      Assign     unknown      TYPE
 14              V_ref_SS Var        unknown      TYPE
 15                       Plus       expression   TYPE
 15                        Neg        expression   TYPE
 15                         Float      float        float  '%(value)s'
 15                        Ifloat     ifloat       TYPE
  0                      Assign     unknown      TYPE
 16                  CSIZ Var        unknown      TYPE
 17              CumThick Get        unknown      TYPE
 17             cplt_index Var        unknown      TYPE   '%(name)s'
 17                        Int        int          int    '%(value)s'
  0                      Assign     unknown      TYPE
 18                   WT0 Var        unknown      TYPE
 19    EMIT_Init_CsgThick Get        unknown      TYPE
 19                   CSIZ Var        unknown      TYPE   '%(name)s'
 19               CumThick Get        unknown      TYPE   ('%(name)s(', ', ', ')')
 19              cplt_index Var        unknown      TYPE   '%(name)s'
 19                         Int        int          int    '%(value)s'
  0                      Assign     unknown      TYPE
 20                   WT1 Var        unknown      TYPE
 21                       Plus       expression   TYPE
 21               CumThick Get        unknown      TYPE   ('%(name)s(', ', ', ')')
 21              cplt_index Var        unknown      TYPE   '%(name)s'
 21                         Int        int          int    '%(value)s'
 21                        Neg        expression   TYPE   ('-(', '', ')')
 21                     WT0 Var        unknown      TYPE   '%(name)s'
  0                      Assign     unknown      TYPE
 22                esigma Var        unknown      TYPE
 23                   sig Var        unknown      TYPE
  0               main Func       func_return  TYPE
  2                     Declares   func_return  TYPE
  2              _retval Declare    int          int
  3                     Returns    func_return  TYPE
  3              _retval Var        int          int
  4                     Params     func_return  TYPE
  4                 argc Var        int          int
  4                 argv Var        char         char
  5                     Block      code_block   TYPE
  0                      Assign     unknown      TYPE
 24               _retvar Var        int          int
 25                       Int        int          int

Traceback (most recent call last):
  File "D:\Projects\emc2\matlab2cpp\mconvert.py", line 39, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 222, in main
    tree.generate(disp=disp)
  File "C:\Python27\lib\site-packages\matlab2cpp\node.py", line 97, in generate
    raise KeyError("no %s in %s" % (cls, backend))
KeyError: 'no Ifloat in ifloat'

**Comment by jonathf** [comment]
Ifloat er imaginært flytall. Det har jeg ikke implementert ennå. Men jeg skal nok få til det til uken.

Jeg har ikke brukt complex i C++ før. Har du en enkel oversikt jeg kan bruke?
Evt. kan du oversette følgende snutt for meg til C++/Armadillo:
a = 3i
b = a + 3
c = [1, 2i]

**Comment by aronandersson** [comment]
Ok, men för template_set.m får jag:

reading file...
running preproc...
writing preproc...
building token-tree...
writing pickle...
writing backup...
cfg found!
loading cfg...
loading scope...
dumping scope...
generate tree...
iterating 133 nodes
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Colon TYPE expression
 Int int int
 Int int int
 Colon TYPE expression
 Colon TYPE expression
 All TYPE expression
 All TYPE expression
 Colon TYPE expression
 Colon TYPE expression
 All TYPE expression
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Colon TYPE expression
 Int int int
 Int int int
 Int int int
 Int int int
 Int int int
 Colon TYPE expression
 Int int int
 Int int int
 Int int int
 Colon TYPE expression
 All TYPE expression
 Int int int
 Int int int
 Int int int
 All TYPE expression
 Colon TYPE expression
 Int int int
 Int int int
 Int int int
 Colon TYPE expression
 Int int int
 Int int int
 Int int int
 All TYPE expression
 Int int int
_retvar Var int unknown
 Int int int
 Sets TYPE code_block
 Int int int
 Sets TYPE code_block
 Int int int
 Sets TYPE code_block
 Int int int
 Sets TYPE code_block
 Int int int
 Sets TYPE code_block
 Int int int
 Sets TYPE code_block
 Int int int
 Sets TYPE code_block
 Colon TYPE expression
 Sets TYPE code_block
 Colon TYPE expression
 Sets TYPE code_block
 Colon TYPE expression
 Sets TYPE code_block
 Colon TYPE expression
 Sets TYPE code_block
 Colon TYPE expression
 Sets TYPE code_block
 Colon TYPE expression
 Sets TYPE code_block
 Colon TYPE expression
 Sets TYPE code_block
 Assign TYPE unknown
x Set TYPE unknown
iterating 134 nodes
 35           program Program    program      TYPE
  1                    Includes   program      TYPE
  1           armadillo Include    program      TYPE
  1           usingarma Include    program      TYPE
  1   span_int_int_ivec Include    program      TYPE
  0               main Func       func_return  TYPE
  2                     Declares   func_return  TYPE
  2              _retval Declare    int          int
  3                     Returns    func_return  TYPE
  3              _retval Var        int          int
  4                     Params     func_return  TYPE
  4                 argc Var        int          int
  4                 argv Var        char         char
  5                     Block      code_block   TYPE
  0                    x Set        unknown      TYPE
  6                       Sets       code_block   TYPE   ('', ', ', '')
  6                        All        expression   TYPE   '&='
  7                       Colon      expression   ivec   ('span(', ', ', ')')
  7                        Int        int          int    '%(value)s'
  7                        Int        int          int    '%(value)s'
  7                        Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
  8                       Sets       code_block   ivec   ('', ', ', '')
  8                        Colon      expression   ivec   ('span(', ', ', ')')
  8                         Int        int          int    '%(value)s'
  8                         Int        int          int    '%(value)s'
  8                         Int        int          int    '%(value)s'
  9                       Colon      expression   ivec   ('span(', ', ', ')')
  9                        Int        int          int    '%(value)s'
  9                        Int        int          int    '%(value)s'
  9                        Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 10                       Sets       code_block   TYPE   ('', ', ', '')
 10                        Colon      expression   ivec   ('span(', ', ', ')')
 10                         Int        int          int    '%(value)s'
 10                         Int        int          int    '%(value)s'
 10                         Int        int          int    '%(value)s'
 10                        All        expression   TYPE   '&='
 11                       Colon      expression   ivec   ('span(', ', ', ')')
 11                        Int        int          int    '%(value)s'
 11                        Int        int          int    '%(value)s'
 11                        Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 12                       Sets       code_block   TYPE   ('', ', ', '')
 12                        All        expression   TYPE   '&='
 12                        Colon      expression   ivec   ('span(', ', ', ')')
 12                         Int        int          int    '%(value)s'
 12                         Int        int          int    '%(value)s'
 12                         Int        int          int    '%(value)s'
 13                       Colon      expression   ivec   ('span(', ', ', ')')
 13                        Int        int          int    '%(value)s'
 13                        Int        int          int    '%(value)s'
 13                        Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 14                       Sets       code_block   ivec   ('', ', ', '')
 14                        Colon      expression   ivec   ('span(', ', ', ')')
 14                         Int        int          int    '%(value)s'
 14                         Int        int          int    '%(value)s'
 14                         Int        int          int    '%(value)s'
 14                        Int        int          int    '%(value)s'
 15                       Colon      expression   ivec   ('span(', ', ', ')')
 15                        Int        int          int    '%(value)s'
 15                        Int        int          int    '%(value)s'
 15                        Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 16                       Sets       code_block   ivec   ('', ', ', '')
 16                        Int        int          int    '%(value)s'
 16                        Colon      expression   ivec   ('span(', ', ', ')')
 16                         Int        int          int    '%(value)s'
 16                         Int        int          int    '%(value)s'
 16                         Int        int          int    '%(value)s'
 17                       Colon      expression   ivec   ('span(', ', ', ')')
 17                        Int        int          int    '%(value)s'
 17                        Int        int          int    '%(value)s'
 17                        Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 18                       Sets       code_block   int    ('', ', ', '')
 18                        Int        int          int    '%(value)s'
 18                        Int        int          int    '%(value)s'
 19                       Colon      expression   ivec   ('span(', ', ', ')')
 19                        Int        int          int    '%(value)s'
 19                        Int        int          int    '%(value)s'
 19                        Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 20                       Sets       code_block   TYPE   ('', ', ', '')
 20                        All        expression   TYPE   '&='
 21                       Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 22                       Sets       code_block   ivec   ('', ', ', '')
 22                        Colon      expression   ivec   ('span(', ', ', ')')
 22                         Int        int          int    '%(value)s'
 22                         Int        int          int    '%(value)s'
 22                         Int        int          int    '%(value)s'
 23                       Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 24                       Sets       code_block   TYPE   ('', ', ', '')
 24                        Colon      expression   ivec   ('span(', ', ', ')')
 24                         Int        int          int    '%(value)s'
 24                         Int        int          int    '%(value)s'
 24                         Int        int          int    '%(value)s'
 24                        All        expression   TYPE   '&='
 25                       Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 26                       Sets       code_block   TYPE   ('', ', ', '')
 26                        All        expression   TYPE   '&='
 26                        Colon      expression   ivec   ('span(', ', ', ')')
 26                         Int        int          int    '%(value)s'
 26                         Int        int          int    '%(value)s'
 26                         Int        int          int    '%(value)s'
 27                       Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 28                       Sets       code_block   ivec   ('', ', ', '')
 28                        Colon      expression   ivec   ('span(', ', ', ')')
 28                         Int        int          int    '%(value)s'
 28                         Int        int          int    '%(value)s'
 28                         Int        int          int    '%(value)s'
 28                        Int        int          int    '%(value)s'
 29                       Int        int          int    '%(value)s'
  0                    x Set        unknown      TYPE
 30                       Sets       code_block   ivec   ('', ', ', '')
 30                        Int        int          int    '%(value)s'
 30                        Colon      expression   ivec   ('span(', ', ', ')')
 30                         Int        int          int    '%(value)s'
 30                         Int        int          int    '%(value)s'
 30                         Int        int          int    '%(value)s'
 31                       Int        int          int    '%(value)s'
  0                    x Set        int          int
 32                       Sets       code_block   int    ('', ', ', '')
 32                        Int        int          int    '%(value)s'
 32                        Int        int          int    '%(value)s'
 33                       Int        int          int    '%(value)s'
  0                      Assign     int          int    '%(0)s = %(1)s ;'
 34               _retvar Var        int          int    '%(name)s'
 35                       Int        int          int    '%(value)s'

Traceback (most recent call last):
  File "D:\Projects\emc2\matlab2cpp\mconvert.py", line 39, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 222, in main
    tree.generate(disp=disp)
  File "C:\Python27\lib\site-packages\matlab2cpp\node.py", line 97, in generate
    raise KeyError("no %s in %s" % (cls, backend))
KeyError: 'no Set in int'

Jag hat inte använt komplexa tal i C++ särskilt mycket själv men någonting sånt här borde fungera:

using namespace arma;

cx_double a(0,3);
cx_double b(1, 3);
cx_double _c[] = {cx_double(1,0),cx_double(0,2)};
cx_rowvec c(_c, 2, 0);

**Comment by jonathf** [comment]
Lager ny issue for dette problemet.
