### ISSUE TITLE
Komplexa skalærer

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#35]
Jag førstår inte riktigt vilket typnamn jag skall anvænda før komplexa skalærer. std::complex<float/double>  ær typedeffad till cx_float/cx_double i armadillo, dessa namn ær att føredra.

**Comment by jonathf** [comment]
Endret til cx_double nå.

Hvis brukeren skriver inn imaginære tall (e.g. "a = 4i") oversetter jeg det til:

    #include <complex>
    #include <cmath>
og
    cx_double a ;
    a = 4*sqrt(-1) ;

Gi lyd hvis det er okay, så lukker jeg saken.

**Comment by aronandersson** [comment]
Jag har fortfarande problem:

cfg found!
loading cfg...
loading scope...
iterating 127 nodes
Traceback (most recent call last):
  File ".\mconvert.py", line 53, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 148, in main
    tree.configure(suggestion=suggestion, disp=disp)
  File "C:\Python27\lib\site-packages\matlab2cpp\node.py", line 314, in configure
    node.generate(False, None)
  File "C:\Python27\lib\site-packages\matlab2cpp\node.py", line 160, in generate
    target = targets.__dict__[backend]
KeyError: 'cx_double'


Du behøver inte inkludera <complex> eller <cmath>, det føljer med armadillo. sqrt(-1) ær inte lagligt i c++, man måste skriva cx_double(0,1). Komplexa tal med enkel precision verkar fortfarande saknas, dvs cx_float, cx_fvec etc...

**Comment by jonathf** [comment]
Ah. Glemte å legge til cx_double i git. Lagt til nå.

byttet sqrt(-1) med cx_double(0,1)

Complexe tall med enkel presisjon (og integers) er ikke støttet. Bjørn sa i mars om at det ikke var noe jeg skulle bruke tid på. Men hvis det er av interesse, lag et nytt issue med prioritet.

**Comment by aronandersson** [comment]
Fungerar fortfarande inte:

Traceback (most recent call last):
  File ".\mconvert.py", line 53, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 148, in main
    tree.configure(suggestion=suggestion, disp=disp)
  File "C:\Python27\lib\site-packages\matlab2cpp\node.py", line 257, in configure
    node.type = [n.type for n in node]
 File "C:\Python27\lib\site-packages\matlab2cpp\datatype.py", line 235, in __set__
    value = common_strict(value)
  File "C:\Python27\lib\site-packages\matlab2cpp\datatype.py", line 88, in common_strict
    dims_ = map(get_dim, vals)
  File "C:\Python27\lib\site-packages\matlab2cpp\datatype.py", line 110, in get_dim
    raise ValueError("%s not recognized" % val)
ValueError: cx_double not recognized

**Comment by jonathf** [comment]
Prøv nå.

**Comment by aronandersson** [comment]
Ok, det fungerar bættre nu.  Mindre problem:

a = 5 + 3i;
b = 5 + 3*i;

øversætts till:

cx_double a = 5 + cx_double(0,3i);
cx_double b = 5 + 3*i;

Alternativt:
a = 5 + 3 * i;

**Comment by jonathf** [comment]
Siden i er en populær brukt variabel i kode har jeg ikke lyst til å reservere den complex enhet.

Men jeg har nå løst det ved å gjøre en liten endring til konfigurasjonen. Dermed er denne løsningen gyldig for alle variabler som er reservert.

Som følger. Hvis en variabel blir assignet (eller en funk-parameter):

    i = 2
    a = i+2

blir til

    i = 2 ;
    a = i+2 ;

Men hvis ingen assignment blir funnet, kicker reserved inn:

    a = i+2

Blir til

    a = cx_complex(0, 1)+2 ;
