### ISSUE TITLE
Paranteser før arrays

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#36]
Arrays genereras nu med [ istællet før {

**Comment by jonathf** [comment]
Gi meg et dummy-eskempel så jeg vet hva du snakker om.

**Comment by aronandersson** [comment]
Nu skrivs arrays som:

double a[] = [1, 2, 3];

Det ska vara:

double a[] = {1,2,3};

**Comment by jonathf** [comment]
Ah.

Fikset nå.

**Comment by aronandersson** [comment]
Uppenbarligen inte fixat i github

**Comment by aronandersson** [comment]
woops, hade inte uppdaterat ordentligt
