### ISSUE TITLE
Medlemsfunktioner på returværden

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#37]
Som jag misstænkte, så går det inte att anvænda medlemsfunktioner på returværden, e.g.

vec a,b;
//...
double m = (a - b).min(i);

Det ær førmodligen bæst att anvænda auxvariabler før detta, med några undantag e.g. "length"

**Comment by jonathf** [comment]
Lagt inn nå for size, min, max.

**Comment by aronandersson** [comment]
Fortfarande inte fixat (på github)
