### ISSUE TITLE
"ctranspose"

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#38]
arma::ctranspose existerar inte vad jag kan se. arma::trans har samma beteende som Matlab's " ' ", dvs den konjugerar komplexa tal. 

Før transponater utan konjugering, se hær:

http://se.mathworks.com/help/matlab/ref/transpose.html

I armadillo gør man detta med arma::strans

**Comment by jonathf** [comment]
Indeed.

Fikset nå.

**Comment by aronandersson** [comment]
Nu har det blivit omvänt, det blir strans där det skall vara trans och vice versa

**Comment by jonathf** [comment]
Fixed.
