### ISSUE TITLE
Space-delimited arrays

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#40]
Matriser med spaces verkar inte fungera ordentligt, e.g.:

    table_c0 = [-5.7464056e-001 -1.7258747e+000  2.6218840e-001  9.0539518e+000  2.3701994e+001  4.0885019e+001  5.7807985e+001  7.3099228e+001  8.6518614e+001  9.8410474e+001  1.0928526e+002  1.1959656e+002  1.2966413e+002  1.3967640e+002 -9.6035336e+001 -8.4252935e+001  8.5867497e+001  2.0760709e+002  3.3567500e+002  5.5549526e+002  5.6674794e+002;...
                -1.3296734e+000 -1.2994901e+000  4.4856099e+000  1.7028611e+001  3.3555982e+001  5.0830573e+001  6.6879385e+001  8.1055147e+001  9.3519651e+001  1.0475133e+002  1.1524267e+002  1.2537096e+002  1.3537617e+002 -1.3992341e+001 -1.1480736e+002 -1.2665120e+001  2.0331357e+002  3.3143621e+002  4.5468520e+002  5.6156409e+002  6.4008560e+002;...
                -1.6787950e+000 -2.6240445e-001  7.7809302e+000  2.1953869e+001  3.9014466e+001  5.6039370e+001  7.1512955e+001  8.5104412e+001  9.7120016e+001  1.0806544e+002  1.1840365e+002  1.2846707e+002  1.3845702e+002 -9.7277928e+001 -8.5489642e+001  8.4709102e+001  2.0662483e+002  3.3487015e+002  5.5446527e+002  5.6430494e+002  6.4125935e+002;...
                -1.7766566e+000  1.4718325e+000  1.1697606e+001  2.7150850e+001  4.4445653e+001  6.1072196e+001  7.5942173e+001  8.8983476e+001  1.0060254e+002  1.1130843e+002  1.2152639e+002  1.3154456e+002 -1.7850622e+001 -1.1870572e+002 -1.6595704e+001  8.7923531e+001  3.2753626e+002  4.5082915e+002  5.5763308e+002  6.3573259e+002  6.4192903e+002];

blir till:

    double _table_c0 [] = {-(5.7464056e-001)-1.7258747e+000-9.6035336e+001-8.4252935e+001, -(1.3296734e+000)-1.2994901e-1.3992341e.1480736e+1.2665120e+001, -(1.6787950e+000)-2.6240445e-001-9.7277928e+001-8.5489642e+001, -(1.7766566e+000)-1.7850622e.1870572e+1.6595704e+001} ;
    table_c0 = mat(_table_c0, 4, 1, false) ;

**Comment by jonathf** [comment]
Space delimiting er vanskelig. Men jeg tror jeg fikk hasen på den nå.

**Comment by aronandersson** [comment]
Jag får krascher med føljande medellande i filer med många space delimited arrayer:

Traceback (most recent call last):
  File ".\mconvert.py", line 53, in <module>
    tree = matlab2cpp.main(path, opt.suggestion, disp=opt.display)
  File "C:\Python27\lib\site-packages\matlab2cpp\__init__.py", line 149, in main
    tree.generate(disp=disp)
  File "C:\Python27\lib\site-packages\matlab2cpp\node.py", line 160, in generate
    target = targets.__dict__[backend]
KeyError: 'struct'

I tillægg så får jag extrema mængder med output (i konsollen)

**Comment by jonathf** [comment]
Dette er en feil i den nye håndteringen av strukts, ikke i space-delimiter.
