### ISSUE TITLE
Submatriser

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#44]
Submatriser fungerar inte längre, e.g.:

    function y = EMIT_Proc_Mandrel_Simulated_LS(x)
    
        y(:,1) = x;
        y(1,:) = x;
        y(2:3,:) = x;
        
    return

blir:

    #include <armadillo>
    using namespace arma ;
    
   
    
    mat EMIT_Proc_Mandrel_Simulated_LS(vec x)
    {
      mat y ;
      y(span::all) = x ;
      y(1) = x ;
      y(span(2, 3)) = x ;
      return y ;
      return y ;
    }

**Comment by jonathf** [comment]
Arma-modulen er omskrevet (i forbindelse med støtte for Cube).
Litt annen struktur, men så vidt jeg kan se, gyldig kode. Ta en titt nå.
