### ISSUE TITLE
-1 på index i span

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#46]
function y = EMIT_Proc_Mandrel_Simulated_LS(x)
    
        y(2,5:end) = x;
        
    return

    mat EMIT_Proc_Mandrel_Simulated_LS(vec x)
    {
      mat y ;
      y(span(1), span(5, y.n_cols)) = (x).t() ;
      return y ;
      return y ;
    }

**Comment by jonathf** [comment]
Hvordan tenkte vi at skulle løse denne?

    y(span(1), span(5, y.n_cols)-1)

eller

    y(span(1), span(5-1, y.n_cols-1))

Første er mer allsidig og kan brukes i flere tilfeller, men krever at jeg legger inn mer auxillary variabler. Sistnevnte dekker ikke alle cases siden span kan innemellom være black-box.

**Comment by aronandersson** [comment]
Vad menar du med "black-box"?

**Comment by jonathf** [comment]
x(1:5)

Her kan jeg fra kotekst se hva som skjer.

    a = 1:5
    x(a)

Her er inneholdet i a ukjent, en black box.

**Comment by aronandersson** [comment]
Ok, jag ser fortfarande inte riktigt vad problemet är. Jag förstår att det finns situationer där arma::span inte är tillräckligt flexibel, men jag ser inte hur det är relaterat till black box problematiken.

    a = 1:5
    y = x(a)
    y = x(a(1):a(5))
    
    uvec a = matlib::span(1,5);
    y = x(a-1)
    y = x(arma::span(a(0)-1,a(4)-1))

**Comment by jonathf** [comment]
Ah. Du vil ha begge deler. Okay. Ikke lengre en quick-fix, but I can do.

**Comment by jonathf** [comment]
Halveis:
`-1` er lagt inn hvis i argumentet.

**Comment by jonathf** [comment]
Hm... Innså at du skrev matlib.
Hittil har jeg ungått å bruke WG proprietær kode.
Ikke noe problem i utgang, men jeg hadde et håp om at lav-nivå ting som span skulle slippe å være bundet til proprietær kode.

Evt. er kanskje ikke den biten proprietær?

**Comment by jonathf** [comment]
Den andre halvdelen. F.eks.:

    v = 1:8
    a(v,1:8,ii)

blir nå til til:

    v = span(1, 8) ;
    _aux_uvec_1 = conv_to<uvec>::from(v) ;
    a(_aux_uvec_1-1, span(0, 7), span(ii-1)) ;
