### ISSUE TITLE
Konvertering till heltalstyp

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#50]
Konverteringar från flyttal till heltal är inte implementerat. e.g.:

    function y = ft(x)
    y = x;
    y = floor(x);
    
    v = 1:10;
    
    y = v(y);
    
    end

bör fungera även om y definieras som int.

Det kan vara bra att definiera en extra funktion för att förhindra konverteringar som är olagliga i Matlab:

    template<iT,fT>
    inline iT ftoi(fT x) {
        arma_extra_debug_sigprint();
        iT ret = iT(x)
        arma_debug_check(x == (fT)ret, "ftoi(): Number must be equal to an integer in Matlab-style conversion.");
        return iT(x);
    }

**Comment by jonathf** [comment]
Dette bryter med et par instruksjoner fra Bjørn.

Vi bl i utgangspunktet enige om at oppkonerteringer (int -> double) skulle ignoreres og nedkonverteringer (double -> int) skulle lage feilmelding i log:

    2 1 Warning in Assign: Type conversion (int) and (double)
    "y = x;"

Andre problemet med forslaget ditt er at det krever en støttefunksjon. Bjørn spurte eksplisit om å ungå dette og kun bruke suppliment fil som antas i bruk ved siden av. En slik snippet passer inn der.

**Comment by jonathf** [comment]
Resolved
