### ISSUE TITLE
Problem med Initialisering/konkatenering

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#51]
Initialisering av tomma matriser, samt konkatenering verkar inte fungera.

	function y = foo(x)
	
	a = [];
	a = [a,x];
	
	end

blir

	int foo(int x)
	{
	  int y ;
	  ivec a ;
	  a = {} ;
	  a =  ;
	  return y ;
	}

**Comment by jonathf** [comment]
Prøv nå
