### ISSUE TITLE
Sortering av variabler i .m.py

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#68]
Det vore bra om variabelnamnen kunde sorteras i bokstavsordning i .m.py-filen. Eftersom Matlab listar variablerna i sitt "workspace" i bokstavsordning skulle det bli enklare att sätta de korrekta typerna för funktioner med många variabler genom att köra koden i matlab.

**Comment by jonathf** [comment]
Godt forslag.
Lagt til nå.
