### ISSUE TITLE
Output file not generated

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#72]
It seems that the output .cpp file is not generated automatically now. Also the includes don't seem to work.

**Comment by jonathf** [comment]
Hvis koden består av funksjoner, genereres ikke .cpp (som nevnt i sist oppdateringsmail). Min tanke her er å lage et tydelig skille mellom hva som er kjørbar kode og hva som er bibliotek. Men jeg kan lett endre dette hvis det er ønske for det.

På hvilken måte fungerer ikke includes?

**Comment by aronandersson** [comment]
ok, ursäkta förvirringen
