### ISSUE TITLE
Files not working if there are comments before the code starts

### ISSUE THREAD

**Issue by aronandersson** [jonathf/matlab2cpp#74]
Filer där det finns kommentarer innan själva koden fungerar inte (.py filen innehåller inget vettigt). e.g.:

    %comment
    y = function (x)
    y = x

**Comment by jonathf** [comment]
Kommentarer skaper krøll før dokumentet er klassifisert som script og function.

Jeg løser dette nå ved å hoppe over de første kommentarene.
