### ISSUE TITLE
Expected to find rule for 'Assign' in the file '_structs.py'

### ISSUE THREAD

**Issue by UFRJ-Cyfer** [jonathf/matlab2cpp#91]
I have been getting this error ;
KeyError: "Expected to find rule for 'Assign' in the file '_structs.py'"

I have tried editing the file (uncommenting the def Assign(node)), however that does not work. Also tried the same thing on the variables.py file, and did not work. 
I tried re-installing with the edited files but that did not work either 

Is there any workaround ?

Thank you

**Comment by geirpa** [comment]
I will try to solve this. I thought it would work if the if uncommenting in def Assign(node) and re-installing but there are some errors then too. I have not used Matlab structs personally, so could you give a short sample program with structs and the type of assignment you want to do.

I suppose something like this?:
a(1).xval = 2
a(1).yval =  5
a(2).xval = 23
a(2).yval = 52

c = b
